apiVersion: v1
kind: ConfigMap
metadata:
  name: mlforge-config
  namespace: mlforge
data:
  APP_NAME: MLForge
  APP_ENV: kubernetes
  LOG_LEVEL: INFO
  CORS_ORIGINS: "*"
  MLFLOW_TRACKING_URI: http://mlflow.mlforge.svc.cluster.local:5000
  MLFLOW_EXPERIMENT_NAME: customer-churn-classification
  MLFLOW_REGISTERED_MODEL_NAME: churn-model
  DATABASE_URL: postgresql+psycopg2://mlforge:mlforge@postgres:5432/mlforge
---
apiVersion: v1
kind: Secret
metadata:
  name: mlforge-secrets
  namespace: mlforge
type: Opaque
stringData:
  API_KEY: changeme-admin-api-key
  POSTGRES_PASSWORD: mlforge
