apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mlforge-ingress
  namespace: mlforge
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: mlforge.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: mlforge-backend
                port:
                  number: 8000
